### ISSUE TITLE
OPT_SERDES=1 fails implementation

### ISSUE THREAD

**Issue by Ttl** [ZipCPU/sdspi#11]
Implementation with OPT_SERDES=1 fails with error "multiple driver nets". The issue is that `o_mine` is assigned twice in `xsdserdes8x.v`. After removing the second assigment on line 188 implementation succeeds but timing fails.

<details>

<summary>Timing report</summary>

| Name     | Slack | Levels | High Fanout | From                                                                                    | To                                                                                 | Total Delay | Logic Delay | Net Delay | Requirement | Source Clock                  | Destination Clock             | Exception | Clock Uncertainty |
|----------|-------|--------|-------------|-----------------------------------------------------------------------------------------|------------------------------------------------------------------------------------|-------------|-------------|-----------|-------------|-------------------------------|-------------------------------|-----------|-------------------|
| Path 221 | -1.01 | 2      | 3           | ps/sdio_top_0/U0/u_sdfrontend/GEN_WIDE_IO.cmd_serdes/GEN_BIDIRECTIONAL.u_iserdes/CLKDIV | ps/sdio_top_0/U0/u_sdfrontend/GEN_WIDE_IO.cmd_serdes/u_oserdes/T1                  | 2.23        | 0.74        | 1.49      | 2.50        | clk_out1_ps_block_clk_wiz_0_0 | clk_out2_ps_block_clk_wiz_0_0 |           | 0.21              |
| Path 222 | -0.58 | 1      | 3           | ps/sdio_top_0/U0/u_sdio/u_txframe/ck_data_reg[13]/C                                     | ps/sdio_top_0/U0/u_sdfrontend/GEN_WIDE_IO.GEN_WIDE_DATIO[5].io_serdes/u_oserdes/T1 | 1.81        | 0.48        | 1.33      | 2.50        | clk_out1_ps_block_clk_wiz_0_0 | clk_out2_ps_block_clk_wiz_0_0 |           | 0.21              |
| Path 223 | -0.50 | 1      | 41          | ps/sdio_top_0/U0/u_sdio/u_txframe/ck_valid_reg/C                                        | ps/sdio_top_0/U0/u_sdfrontend/GEN_WIDE_IO.GEN_WIDE_DATIO[1].io_serdes/u_oserdes/T1 | 1.73        | 0.63        | 1.10      | 2.50        | clk_out1_ps_block_clk_wiz_0_0 | clk_out2_ps_block_clk_wiz_0_0 |           | 0.21              |
| Path 224 | -0.44 | 1      | 41          | ps/sdio_top_0/U0/u_sdio/u_txframe/ck_valid_reg/C                                        | ps/sdio_top_0/U0/u_sdfrontend/GEN_WIDE_IO.GEN_WIDE_DATIO[2].io_serdes/u_oserdes/T1 | 1.67        | 0.63        | 1.04      | 2.50        | clk_out1_ps_block_clk_wiz_0_0 | clk_out2_ps_block_clk_wiz_0_0 |           | 0.21              |
| Path 225 | -0.41 | 1      | 41          | ps/sdio_top_0/U0/u_sdio/u_txframe/ck_valid_reg/C                                        | ps/sdio_top_0/U0/u_sdfrontend/GEN_WIDE_IO.GEN_WIDE_DATIO[4].io_serdes/u_oserdes/T1 | 1.64        | 0.63        | 1.01      | 2.50        | clk_out1_ps_block_clk_wiz_0_0 | clk_out2_ps_block_clk_wiz_0_0 |           | 0.21              |
| Path 226 | -0.40 | 1      | 41          | ps/sdio_top_0/U0/u_sdio/u_txframe/ck_valid_reg/C                                        | ps/sdio_top_0/U0/u_sdfrontend/GEN_WIDE_IO.GEN_WIDE_DATIO[6].io_serdes/u_oserdes/T1 | 1.63        | 0.63        | 1.00      | 2.50        | clk_out1_ps_block_clk_wiz_0_0 | clk_out2_ps_block_clk_wiz_0_0 |           | 0.21              |
| Path 227 | -0.37 | 1      | 41          | ps/sdio_top_0/U0/u_sdio/u_txframe/ck_valid_reg/C                                        | ps/sdio_top_0/U0/u_sdfrontend/GEN_WIDE_IO.GEN_WIDE_DATIO[7].io_serdes/u_oserdes/T1 | 1.60        | 0.63        | 0.97      | 2.50        | clk_out1_ps_block_clk_wiz_0_0 | clk_out2_ps_block_clk_wiz_0_0 |           | 0.21              |
| Path 228 | -0.30 | 1      | 10          | ps/sdio_top_0/U0/u_sdio/u_control/o_pp_data_reg/C                                       | ps/sdio_top_0/U0/u_sdfrontend/GEN_WIDE_IO.GEN_WIDE_DATIO[3].io_serdes/u_oserdes/T1 | 1.53        | 0.54        | 0.99      | 2.50        | clk_out1_ps_block_clk_wiz_0_0 | clk_out2_ps_block_clk_wiz_0_0 |           | 0.21              |
| Path 229 | -0.29 | 1      | 10          | ps/sdio_top_0/U0/u_sdio/u_control/o_pp_data_reg/C                                       | ps/sdio_top_0/U0/u_sdfrontend/GEN_WIDE_IO.GEN_WIDE_DATIO[0].io_serdes/u_oserdes/T1 | 1.53        | 0.54        | 0.99      | 2.50        | clk_out1_ps_block_clk_wiz_0_0 | clk_out2_ps_block_clk_wiz_0_0 |           | 0.21              |

</details>

Testing it with failed timing, initialization and CSD reading succeeds but bus width determination fails sometimes. When bus width determination succeeds reading and writing single blocks works with enough time after write. Busy workaround of reading o_debug doesn't work since it's all zeroes when using serdes option.

**Comment by ZipCPU** [comment]
This issue may need some more investigation, particularly since [this line](https://github.com/ZipCPU/sdspi/blob/62f0ce9c099c8bf1b7ed894c7daf6a954838c049/rtl/sdfrontend.v#L801-L802) doesn't seem to be appropriately representative at all ... for now, let me ask:

When timing fails, at what (system) clock rate is it failing at?

Also, if/when timing fails, does the design still work for some clock phases?  (i.e. via bits [20:16] of the PHY register)

Dan

**Comment by Ttl** [comment]
System clock is 100 MHz and serdes clock is 400 MHz. Both are generated by the same MMCM. Device is Zynq 7020.

I'll do more testing with serdes when the busy bit is working, but it did seem to be working at least most of the time.

Here is vivado report for the first path in the report with the worst slack:

![timing](https://github.com/user-attachments/assets/54123eb5-2d83-47c1-b565-4c065e7f1624)

**Comment by ZipCPU** [comment]
That appears to be an entirely different path.

**Comment by ZipCPU** [comment]
I'm now getting similar timing errors here.  I haven't yet determined a fix.  For now, know that the OPT_DDR=1, OPT_OSERDES=0, front end should be sufficient for any 3.3V uses.  If I recall correctly, you need 1.8V support to go any faster.

**Comment by Ttl** [comment]
I tested OPT_SERDES with the latest changes and it doesn't seem to work. Occasionally bus width determination fails and it falls back to 1 bit bus. When it succeeds it hangs during write. I didn't try to debug it further.

Synthesis fails with errors:

```
[Synth 8-524] part-select [24:0] out of range of prefix 'ck_sreg' ["sdfrontend.v":819]
[Synth 8-524] part-select [24:0] out of range of prefix 'ck_psreg' ["sdfrontend.v":837]
[Synth 8-524] part-select [24:0] out of range of prefix 'pck_sreg' ["sdfrontend.v":1050]
```

I changed that to `[23:0]` in my tests.

**Comment by ZipCPU** [comment]
I'm working on a fix for this.  It's going to involve a bit of front end redesign.  Specifically, I'm going to remove all tristate logic from the front end, so the tristate signals are instead registered from within the design before arriving at the front end.  This will remove all of the combinatorial tristate logic at the front end.  It will also force you into push-pull mode any time you try to send data faster than 1b per clock (i.e. HS200 and HS400).

If this fails, we'll need to place a false path or other false path timing exception on the 8b tristate paths.

These changes aren't going to happen over night however.  That said, if you have the patience to stick around for this, I'd love to hear the results you get when testing this--since I don't (currently) have any hardware that can move that fast.

Q1: Will you be able to wait a couple weeks for this feature if necessary?

I'm also staring at the data strobe support, and wondering if it needs updating as well--especially to meet timing in a more reliable manner.  Let me ask a second question, then:

Q2: Do you intend to use the return data strobe at all?  It's only present with eMMC devices in HS400.

Finally, since you are using an eMMC device, ...

Q3: Do you foresee a need for the collision option in your application?

Collision detection is designed for the case of a GO_IRQ_STATE instruction for the case where you wish to interrupt the device yourself.

**Comment by Ttl** [comment]
I can test it when it's ready even if it will take a while.

I have return strobe wired to clock capable input pin so I can test it if needed. However, FPGA has adjustable input delay in hardware so I'm not sure if there is any benefit on using strobe instead of tuning the input delay?

I don't see myself needing interrupt support.

**Comment by ZipCPU** [comment]
Have you tried the latest updates at all?  These updates, and particularly d756ce9c97a019e3a39dcee376243954797f0283,  should have fixed the OPT_SERDES support ...

**Comment by Ttl** [comment]
I tried it with the latest code but wasn't able to get it working. In the implementation there are still timing errors to tristate inputs even though it's a straight path from flip-flop. `i_clk` is 100 MHz and `hs_clk` is 400 MHz generated from the same MMCM. Trying the bitstream with failed timing, software gets stuck in `emmc_init -> emmc_go_idle -> emmc_wait_while_busy`. This was with older version of the software that previously worked with the older rtl version. The same software works with `OPT_DDR=1` with the latest rtl.

I also tried the newest software. In the `emmcdrv.c` there are few trivial compile errors. `emmc_dump_err`, `sdio_dump_err` and `SDIO_RXCRCERR` are not defined. Fixing those it gets stuck in [`emmc_init:1565`](https://github.com/ZipCPU/sdspi/blob/master/sw/emmcdrv.c#L1565). Removing the `SDIO_RESET` command makes it get stuck the same place as before.

**Comment by ZipCPU** [comment]
Well, let's work through these issues here.

First, and foremost, you will need some timing exceptions.  [Here are the ones I used to get the design to build](https://github.com/ZipCPU/videozip/blob/0e838618fd9c8964616e663347869784e5fc9395/rtl/board.xdc#L548-L549).  Personally, I don't think these timing exceptions should be required, but ... that's how Xilinx built the part.  As a result, timing is a bit sloppy, but I use a clock cycle to account for it to make sure things work.

I have tested this controller, with this front end, on my [Nexys Video design](https://github.com/ZipCPU/videozip/tree/dev) and it does work.  It should work in the included simulation as well.

Next, your software will likely need a minor upgrade.  At issue is that there's a minimum RESET duration.  Hence when you set and then clear the RESET pin, you may still need to wait for it to be released.  [See these lines for an example](https://github.com/ZipCPU/sdspi/blob/master/bench/testscript/emmclib.v#L521-L528).

As for the `emmc_dump_err()` issue, yeah, let me fix that.  The function should mirror the `sdio_dump_err()` function in the SDIO controller, and ... it looks like I haven't yet built that function for the eMMC controller yet.

Thank you for that feedback.  It is very valuable to me.

**Comment by ZipCPU** [comment]
495a6c8205b2962d2644646f4b616729e3a4872a should fix the software build errors.

**Comment by ZipCPU** [comment]
2d28ccb3f01e921e7067d7fed095c09baacbab23 should fix the initial hardware reset issue, while also guaranteeing the design starts by issuing a hardware reset.

**Comment by Ttl** [comment]
No change with those changes. `sd_cmd` value is 0x4040 when it's stuck at waiting for not busy. Debug port ILA looks like this:
![sdspi_ila](https://github.com/user-attachments/assets/8445d22b-8291-4932-8b49-843588401034)

**Comment by ZipCPU** [comment]
Do you mean the clock to be (nearly) stopped?  What do you get when reading from the PHY register?

**Comment by Ttl** [comment]
phy register is 0xc9000041. This is during `emmc_init` so it should be running at 400 kHz.

**Comment by Ttl** [comment]
It seems that the issue was because I had `OPT_COLLISION` set. Unsetting it like the comment says fixes it and it does work now. I'll do more testing with different bus speeds later.

**Comment by Ttl** [comment]
It seems that switching to 8-bit bus doesn't work:

<details>
<summary>Output</summary>

```
Testing 4b width
CMD6:    SWITCH
CMD13:   SEND_STATUS
  Cmd:     0001010d
  Data:    00000900
  PHY:     c2003403
EMMC R1 Decode:  00000900
  STATE: tran
  READY_FOR_DATA
  Cmd:     00010346
  Data:    00000900
  PHY:     c2003403
CMD19:   BUSTEST_W
  Cmd:     00010113
  Data:    00000900
  PHY:     c2003403
CMD14:   BUSTEST_R
  Cmd:     0001110e
  Data:    00001300
  PHY:     c2003403
 FIFB:     5a000000
  Success!
Testing 8b width
CMD6:    SWITCH
  Cmd:     00010346
  Data:    03b70200
  PHY:     c2003803
CMD13:   SEND_STATUS
  Cmd:     0001010d
  Data:    00000900
  PHY:     c2003803
EMMC R1 Decode:  00000900
  STATE: tran
  READY_FOR_DATA
CMD19:   BUSTEST_W
  Cmd:     00010113
  Data:    00000900
  PHY:     c2003803
CMD14:   BUSTEST_R
  Cmd:     00c1910e
  Data:    00001300
  PHY:     c2003803
 FIFB:     ca250000
  8b fail! (ca250000) -- falling back to 4b
```
</details>

It works with 4-bit bus, but speed is lower than with `OPT_DDR` using 8-bit bus.

**Comment by ZipCPU** [comment]
You should be able to fix the issue by adjusting the sample shift bits of the PHY register--bits [20:16].

**Comment by Ttl** [comment]
That fixed it. HS200@100 MHz works, but HS200@200MHz doesn't work correctly. Write transactions sometimes, but not always, succeeds and TX DMA finishes. RX transaction raises error with CRCERROR bit set (`0x181834c` value reading from `sd_cmd`). I'm using [my `emmc_hs200_tuning`](https://github.com/Ttl/sdspi/blob/emmc_sw/sw/emmcdrv.c#L1079) function for setting delay values for HS200 mode. I tried also manually few other values without success.

Maybe using data strobe would be more reliable at high speeds, but it's only supported in HS400 mode and I haven't implemented switching to it in software.

**Comment by ZipCPU** [comment]
I'm not sure how I would debug the 200MHz issue from here.  Any help you might offer would be useful.  Do we need per-line delays on your IO lines to prevent from corruption at those high speeds?  Or are the wires on your board not reliable?  Or is it something, somewhere, in the IP?

**Comment by Ttl** [comment]
EMMC routing should be fine. It's right next to the FPGA routed with 50 ohm lines. There is max 10 mm length difference from shortest DAT to CLK, with CLK being longer, and 6 mm difference between DAT lines. 10 mm is about 60 ps time difference. Some data lines are routed through unused balls, but that should add capacitance delaying them and bringing them closer to CLK, although that could increase DAT skew.

According to EMMC specifications, HS200@200 MHz device output eye should be at least 2.8 ns in width. Sampling points shift in IP is a multiple of 1.25 ns (DDR rate at 400 MHz `hs_clk`). FPGA MMCM clock p-p jitter is 110 ps and ISERDESE2 on Zynq-7020 needs -20/+170 ps setup/hold. Even with the most unlucky sampling point distribution there should be a sampling point with at least 775 ps margin (or even more if ISERDESE2 hold is the limit), which should be more than enough for device delay + PCB delay + ISERDESE2 window + clock jitter. So in theory I don't think there is a reason to need any finer delay adjustment?

This is how the tuning function output looks like:

<details>
<summary>Output</summary>

```
Shift value, Pass/Fail
0 F
1 F
2 P
3 P
4 F
5 F
6 P
7 P
8 F
9 F
10 P
11 P
12 F
13 F
14 P
15 P
16 F
17 F
18 P
19 P
20 F
21 F
22 P
23 P
24 F
25 F
26 F
27 F
28 F
29 F
30 F
31 F

Largest range: 2 - 3
Setting receiver shift to: 2
```
</details>

There are multiple valid windows where the received data is correct. Does this look correct? Tuning does seem to pass, but somehow RX fails CRC check during the transfer?

Is there easy way to disable RX CRC check so I can check if there is a particular bit that is causing the RX error?

**Comment by ZipCPU** [comment]
Well ... sort of.  Following an RX CRC failure, the received data should still be in the buffer.  You just won't get the CRC.
