### ISSUE TITLE
not checking return address of malloc for validity

### ISSUE THREAD

**Issue by dshekter** [ZipCPU/sdspi#15]
https://github.com/ZipCPU/sdspi/blob/master/sw/sdiodrv.c#L1317
```c
	SDIODRV	*dv = (SDIODRV *)malloc(sizeof(SDIODRV));
	unsigned op_cond_query;
	unsigned	clk_phase = 16 << 16;

	dv->d_dev = dev;
``` 

Color me surprised when my program started freaking out. Naturally it's my own issue on why a malloc is failing when it should pass, but best practice is to check return values from malloc. 

I may put a PR in for this. If I do, I'll probably prefer to also add the option of static allocation (given the DRIVES array is already statically allocated, the number of drivers should be equal to the count of each driver within DRIVES).

**Comment by ZipCPU** [comment]
Fixed in 1171f7db7808e0227b3e9c2982213cd135718e04.
