### ISSUE TITLE
C++ undefined behavior

### ISSUE THREAD

**Issue by mjc0608** [ZipCPU/sdspi#4]
At autotest_tb.cpp:218, this function with return type unsigned does not have a return value. This is undefined behavior of C++. When using g++ 10.2 and -O1, it will be optimized to an infinite loop and trigger an assertion later.

Add "return r;" to the end of the function can solve the problem.

**Comment by ZipCPU** [comment]
Fixed in [ed2e35d](https://github.com/ZipCPU/sdspi/commit/ed2e35dabe3eb841b06c2de7ef250e11ffc9202a).

Thank you!
